services:
  - type: web
    name: fretnow-agi
    runtime: node
    repo: https://github.com/touko501/fretnow-agi
    branch: main
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss
    startCommand: node seed.js && node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        fromDatabase:
          name: transport-token-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://fretnow-agi.onrender.com
      - key: CORS_ORIGINS
        value: https://fretnow-agi.onrender.com
      - key: COMMISSION_PERCENT
        value: "10"
    healthCheckPath: /api/health
    plan: free

databases:
  - name: transport-token-db
    plan: free
    databaseName: fretnow_db
    user: fretnow_user
